version: "3.8"
services:
  mongo-admin:
    image: mongo-express
    container_name: mongo-admin
    depends_on:
      - mongo-db
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: 10.0.10.20
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      om:
        ipv4_address: 10.0.10.9
